namespace ACadSharp
{
	public static class DxfSubclassMarker
	{
		public const string AcDbPlaceHolder = "AcDbPlaceHolder";

		public const string AlignedDimension = "AcDbAlignedDimension";

		public const string Angular2LineDimension = "AcDb2LineAngularDimension";

		public const string Angular3PointDimension = "AcDb3PointAngularDimension";

		public const string AnnotScaleObjectContextData = "AcDbAnnotScaleObjectContextData";

		public const string ApplicationId = "AcDbRegAppTableRecord";

		public const string Arc = "AcDbArc";

		public const string Attribute = "AcDbAttribute";

		public const string AttributeDefinition = "AcDbAttributeDefinition";

		public const string Block1PtParameter = "AcDbBlock1PtParameter";

		public const string Block2PtParameter = "AcDbBlock2PtParameter";

		public const string BlockAction = "AcDbBlockAction";

		public const string BlockBasePointParameter = "AcDbBlockBasePointParameter";

		public const string BlockBegin = "AcDbBlockBegin";

		public const string BlockElement = "AcDbBlockElement";

		public const string BlockEnd = "AcDbBlockEnd";

		public const string BlockFlipAction = "AcDbBlockFlipAction";

		public const string BlockFlipGrip = "AcDbBlockFlipGrip";

		public const string BlockFlipParameter = "AcDbBlockFlipParameter";

		public const string BlockGrip = "AcDbBlockGrip";

		public const string BlockGripExpression = "AcDbBlockGripExpression";

		public const string BlockGripLocationComponent = "AcDbBlockGripLocationComponent";

		public const string BlockLinearParameter = "AcDbBlockLinearParameter";

		public const string BlockParameter = "AcDbBlockParameter";

		public const string BlockRecord = "AcDbBlockTableRecord";

		public const string BlockVisibilityGrip = "AcDbBlockVisibilityGrip";

		public const string BlockVisibilityParameter = "AcDbBlockVisibilityParameter";

		public const string CellStyleMap = "AcDbCellStyleMap";

		public const string Circle = "AcDbCircle";

		public const string DbColor = "AcDbColor";

		public const string DiametricDimension = "AcDbDiametricDimension";

		public const string Dictionary = "AcDbDictionary";

		public const string DictionaryVar = "AcDbDictionaryVar";

		public const string DictionaryVariables = "DictionaryVariables";

		public const string DictionaryWithDefault = "AcDbDictionaryWithDefault";

		public const string Dimension = "AcDbDimension";

		public const string DimensionStyle = "AcDbDimStyleTableRecord";

		public const string DimensionStyleTable = "AcDbDimStyleTable";

		public const string Ellipse = "AcDbEllipse";

		public const string Entity = "AcDbEntity";

		public const string EvalGraph = "AcDbEvalGraph";

		public const string EvalGraphExpr = "AcDbEvalExpr";

		public const string Face3d = "AcDbFace";

		public const string Filter = "AcDbFilter";

		public const string GeoData = "AcDbGeoData";

		public const string Group = "AcDbGroup";

		public const string Hatch = "AcDbHatch";

		public const string Helix = "AcDbHelix";

		public const string Insert = "AcDbBlockReference";

		public const string Layer = "AcDbLayerTableRecord";

		public const string Layout = "AcDbLayout";

		public const string Leader = "AcDbLeader";

		public const string Line = "AcDbLine";

		public const string LinearDimension = "AcDbRotatedDimension";

		public const string Linetype = "AcDbLinetypeTableRecord";

		public const string LwPolyline = "AcDbPolyline";

		public const string Material = "AcDbMaterial";

		public const string Mesh = "AcDbSubDMesh";

		public const string MInsert = "AcDbMInsertBlock";

		public const string MLeaderStyle = "AcDbMLeaderStyle";

		public const string MLine = "AcDbMline";

		public const string MLineStyle = "AcDbMlineStyle";

		public const string ModelerGeometry = "AcDbModelerGeometry";

		public const string MText = "AcDbMText";

		public const string MultiLeader = "AcDbMLeader";

		public const string MultiLeaderObjectContextData = "AcDbMLeaderObjectContextData";

		public const string ObjectContextData = "AcDbObjectContextData";

		public const string OrdinateDimension = "AcDbOrdinateDimension";

		public const string PdfDefinition = "AcDbPdfDefinition";

		public const string PdfReference = "AcDbPdfReference";

		public const string PlotSettings = "AcDbPlotSettings";

		public const string Point = "AcDbPoint";

		public const string PolyfaceMesh = "AcDbPolyFaceMesh";

		public const string PolyfaceMeshFace = "AcDbFaceRecord";

		public const string PolyfaceMeshVertex = "AcDbPolyFaceMeshVertex";

		public const string Polyline = "AcDb2dPolyline";

		public const string Polyline3d = "AcDb3dPolyline";

		public const string Polyline3dVertex = "AcDb3dPolylineVertex";

		public const string PolylineVertex = "AcDb2dVertex";

		public const string ProxyEntity = "AcDbProxyEntity";

		public const string ProxyObject = "AcDbProxyObject";

		public const string RadialDimension = "AcDbRadialDimension";

		public const string RasterImage = "AcDbRasterImage";

		public const string RasterImageDef = "AcDbRasterImageDef";

		public const string RasterImageDefReactor = "AcDbRasterImageDefReactor";

		public const string RasterVariables = "AcDbRasterVariables";

		public const string Ray = "AcDbRay";

		public const string Scale = "AcDbScale";

		public const string Shape = "AcDbShape";

		public const string Solid = "AcDbTrace";

		public const string SortentsTable = "AcDbSortentsTable";

		public const string SpatialFilter = "AcDbSpatialFilter";

		public const string Spline = "AcDbSpline";

		public const string Table = "AcDbSymbolTable";

		public const string TableContent = "AcDbTableContent";

		public const string TableEntity = "AcDbTable";

		public const string TableRecord = "AcDbSymbolTableRecord";

		public const string TableStyle = "AcDbTableStyle";

		public const string Text = "AcDbText";

		public const string TextStyle = "AcDbTextStyleTableRecord";

		public const string Tolerance = "AcDbFcf";

		public const string Trace = "AcDbTrace";

		public const string Ucs = "AcDbUCSTableRecord";

		public const string Underlay = "AcDbUnderlayReference";

		public const string UnderlayDefinition = "AcDbUnderlayDefinition";

		public const string Vertex = "AcDbVertex";

		public const string View = "AcDbViewTableRecord";

		public const string Viewport = "AcDbViewport";

		public const string VisualStyle = "AcDbVisualStyle";

		public const string VPort = "AcDbViewportTableRecord";

		public const string Wipeout = "AcDbWipeout";

		public const string XLine = "AcDbXline";

		public const string XRecord = "AcDbXrecord";
	}
}